config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: "matters#index"
  resources :matters do
      resources :clients, except: [:show]
      resources :business_talk_records, except: [:show]
      resources :sales_staffs, only: [:edit, :update]
    collection do
      get 'search'
      post 'search'
    end
  end
  get 'clients', to: 'matters#new_client'
  post 'clients', to: 'matters#create_client'
  get 'sales_staffs', to: 'matters#new_sales_staff'
  post 'sales_staffs', to: 'matters#create_sales_staff'
  resources :users, only: [:show, :edit, :update]
end

app/models/matter.rb
class Matter < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :priority
  belongs_to_active_hash :progress
  belongs_to_active_hash :reliability

  belongs_to :user, optional: true
  belongs_to :sales_staff, optional: true
  has_many   :matter_clients, dependent: :destroy
  has_many   :clients, through: :matter_clients
  has_many   :business_talk_records, dependent: :destroy

  with_options presence: true do
    validates :matter_name
    validates :product
    validates :sale_time
    validates :priority_id, numericality: { other_than: 0, message: 'を選択してください' }
    validates :reliability_id, numericality: { other_than: 0, message: 'を選択してください' }
    validates :progress_id, numericality: { other_than: 0, message: 'を選択してください' }
    validates :occasion
  end

  validates :sale_price, numericality: { only_integer: true }, allow_blank: true
  validates :profit_price, numericality: { only_integer: true }, allow_blank: true
end

app/controllers/matters_controller.rb
class MattersController < ApplicationController
  before_action :matter_find, only: [:show, :edit, :update, :destroy]

  def index
    @matters = Matter.includes(:user).all.order(updated_at: 'DESC')
  end

  def new
    @matter = Matter.new
  end

  def create
    @matter = Matter.new(matter_params)
    render :new and return unless @matter.valid?

    session['matter_data'] = { matter: @matter.attributes }
    redirect_to clients_path
  end

  def new_client
    @client = Client.new
  end

  def create_client
    @client = Client.new(client_params)
    render :new_client and return unless @client.valid?

    session['client_data'] = { client: @client.attributes }
    redirect_to sales_staffs_path
  end
  
  def new_sales_staff
    @sales_staff = SalesStaff.new
  end

  def create_sales_staff
    @matter = Matter.new(session['matter_data']['matter'])
    @client = Client.new(session['client_data']['client'])
    @sales_staff = SalesStaff.new(sales_staff_params)

    render :new_sales_staff and return unless @sales_staff.valid?

    @sales_staff.save
    @matter.sales_staff_id = @sales_staff.id
    @matter.save
    @client.save
    MatterClient.create(matter_id: @matter.id, client_id: @client.id)
    redirect_to root_path
  end

  def edit
    redirect_to matter_path unless current_user.administrator_id == 2 || @matter.user == current_user
  end

  def update
    if @matter.update(matter_params)
      redirect_to matter_path(@matter)
    else
      render :edit
    end
  end

  def search
    @priority_id = Priority.where.not(id: 0)
    @reliability_id = Reliability.where.not(id: 0)
    @progress_id = Progress.where.not(id: 0)
    if params[:commit] == 'リセット'
      @q = Matter.ransack
      @matters = @q.result
    elsif params[:user_id].present?
      user = User.find(params[:user_id])
      params[:q] = { user_family_name_or_user_first_name_cont: user.family_name + user.first_name }
      @matters = Matter.where(user_id: user.id)
      @q = Matter.ransack(params[:q])
    elsif params[:q].present?
      if params[:q][:user_family_name_or_user_first_name_cont].present?
        users = User.where('concat(family_name, first_name) LIKE(?)', "%#{params[:q][:user_family_name_or_user_first_name_cont]}%")
        @matters = Matter.where(user_id: users.ids)
        @q = Matter.ransack(params[:q])
      else
        @q = Matter.ransack(params[:q])
        @matters = @q.result
      end
    else
      params[:q] = { sorts: 'id desc' }
      @q = Matter.ransack
      @matters = @q.result
    end
  end

  def destroy
    redirect_to matter_path unless current_user.administrator_id == 2 || @matter.user == current_user
    @sales_staff = SalesStaff.find(@matter.sales_staff_id)
    @matter_clients = MatterClient.where(matter_id: params[:id])
    @matter_clients.each do |matter_client|
      if MatterClient.where(client_id: matter_client.client_id).count == 1
        @client = Client.find(matter_client.client_id)
        @client.destroy
      end
    end
    @matter.destroy
    @sales_staff.destroy unless Matter.where(sales_staff_id: @sales_staff.id).present?
    redirect_to root_path
  end

  private

  def matter_params
    require 'date'
    params.require(:matter).permit(:matter_name, :matter_explain, :product, :sale_price, :profit_price, :sale_time, :priority_id, :reliability_id, :progress_id, :occasion).merge(user_id: current_user.id, updated_daytime: DateTime.now)
  end

  def client_params
    params.require(:client).permit(:company, :department, :name)
  end

  def sales_staff_params
    params.require(:sales_staff).permit(:department, :staff)
  end

  def matter_find
    @matter = Matter.find(params[:id])
  end
end

app/helpers/matters_helper.rb
module MattersHelper
end

app/views/matters/edit.html.erb
<body>
  <div class='matter'>
    <div class='matter-title'>
      <h2>案件情報を編集してください</h2>
    </div>
    <div class="matter-main">
      <%= form_with model: @matter, url: matter_path ,class:"matter-forms", local: true do |f|  %>
      <%= render partial: "shared/matter_form", locals: { f: f } %>
      <div>
        <%= f.submit "案件情報編集",class:"matter-button"%>
      </div>
      <% end %>
    </div>
  </div>
</body>

app/views/matters/index.html.erb
<%= render "shared/header" %>
<div class="top-main">
  <div class="main-title">
    最近10件の更新案件
  </div>
  <div class="matter-lists">
    <% @matters.first(10).each do |matter| %>
    <%= render partial: "shared/matter_list", locals: {matter: matter}%>
    <%end%>
  </div>
</div>
<%= render "shared/footer" %>

app/views/matters/new.html.erb
<body>
  <div class='matter'>
    <div class='matter-title'>
      <h2>新規案件を登録してください</h2>
    </div>
    <div class="matter-main">
      <%= form_with model: @matter, url: matters_path, class:"matter-forms", local: true do |f|  %>
      <%= render partial: "shared/matter_form", locals: { f: f } %>
      <div>
        <%= f.submit "顧客情報登録へ",class:"matter-button"%>
      </div>
      <% end %>
    </div>
  </div>
</body>

app/views/matters/new_client.html.erb
<body>
  <div class='matter'>
    <div class='matter-title'>
      <h2>顧客情報を登録してください</h2>
    </div>
    <div class="matter-main">
      <%= form_with model: @client, url:clients_path, class:"matter-forms", local: true do |f|  %>
      <%= render partial: "shared/client_form", locals: { f: f } %>
      <div>
        <%= f.submit "担当営業の登録へ" ,class:"user-button" %>
      </div>
      <% end %>
    </div>
  </div>
</body>

app/views/matters/new_sales_staff.html.erb
<body>
  <div class='matter'>
    <div class='matter-title'>
      <h2>担当営業を登録してください</h2>
    </div>
    <div class="matter-main">
      <%= form_with model: @sales_staff, url:sales_staffs_path, class:"matter-forms", local: true do |f|  %>
      <%= render partial: "shared/sales_staff_form", locals: { f: f } %>
      <div>
        <%= f.submit "登録" ,class:"user-button" %>
      </div>
      <% end %>
    </div>
  </div>
</body>

app/views/matters/search.html.erb
<%= render "shared/header" %>
<div class="matter-information">
  <div class="search-sidebar">
    <%= search_form_for @q, url:search_matters_path, class: 'search-form' do |f| %>
    <%= render partial: "shared/matter_search_form", locals: {f: f}%>
  </div>
  <div class="search-main">

    <% if @matters.length !=0 %>
    <% @matters.each do |matter| %>
    <%= render partial: "shared/matter_list", locals: {matter: matter}%>
    <% end %>
    <% else %>
    該当する案件はありません
    <% end %>
    <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/matters/show.html.erb
<%= render "shared/header" %>
<div class="matter-information">
  <%= render partial:"shared/matter_information_side" , locals: { matter: @matter }%>
  <div class="left-side">
    <h2><%= @matter.matter_name %>
    </h2>
    <p class="matter-time">
      <%= "#{@matter.updated_at.strftime("%Y-%m-%d %H:%M")}更新" %>
    </p>
    <table class="matter-information-table">
      <tr class="matter-information-table-row-high">
        <th>案件詳細</th>
        <td class="overflow">
          <%= simple_format(@matter.matter_explain) %>
        </td>
      </tr>
      <tr class="matter-information-table-row-low">
        <th>商材名</th>
        <td><%= @matter.product %></td>
      </tr>
      <tr class="matter-information-table-row-low">
        <th>販売金額見込み(千円)</th>
        <td><% if @matter.sale_price.present? %>
          <%= "¥#{@matter.sale_price.to_s(:delimited, delimiter: ',')}" %>
          <% else %>
          未定
          <% end %>
        </td>
      </tr>
      <tr class="matter-information-table-row-low">
        <th>利益見込み(千円)</th>
        <td><% if @matter.profit_price.present? %>
          <%= "¥#{@matter.profit_price.to_s(:delimited, delimiter: ',')}" %>
          <% else %>
          未定
          <% end %></td>
      </tr>
      <tr class="matter-information-table-row-low">
        <th>販売見込み時期</th>
        <td><%= "#{@matter.sale_time.strftime("%Y")}年#{@matter.sale_time.strftime("%m")}月" %></td>
      </tr>
      <tr class="matter-information-table-row-low">
        <th>重点度</th>
        <td><%= @matter.priority.name %></td>
      </tr>
      <tr class="matter-information-table-row-low">
        <th>確度</th>
        <td><%= @matter.reliability.name %></td>
      </tr>
      <tr class="matter-information-table-row-low">
        <th>進捗</th>
        <td><%= @matter.progress.name %></td>
      </tr>
      <tr class="matter-information-table-row-low">
        <th>きっかけ</th>
        <td><%= @matter.occasion %></td>
      </tr>
      <tr class="matter-information-table-row-low">
        <th>担当者</th>
        <td><%= @matter.user.family_name %><%= @matter.user.first_name %>
        </td>
      </tr>
    </table>
    <h2>担当営業情報</h2>
    <table class="matter-information-table">
      <tr class="matter-information-table-row-low">
        <th>部署・役職</th>
        <td><%= @matter.sales_staff.department %></td>
      </tr>
      <tr class="matter-information-table-row-low">
        <th>営業スタッフ</th>
        <td><%= @matter.sales_staff.staff %></td>
      </tr>
    </table>
  </div>
  <div class="right-side">
    <div class="right-side-top">
      <h2>顧客情報</h2>
      <p class="client-delete-message"><%= flash[:client_success] %></p>
      <p class="client-delete-message"><%= flash[:client_failure] %></p>
      <% @matter.matter_clients.first(2).each do |matter_client| %>
      <%= render partial: "shared/client_list", locals: { matter_client: matter_client } %>
      <% end %>
      <div class="all-client">
        <%= link_to "この案件の顧客情報一覧を開く", matter_clients_path(@matter.id), class:"all-client-link" %>
      </div>
    </div>
    <div class="right-side-bottom">
      <h2>商談記録</h2>
      <p class="client-delete-message"><%= flash[:business_talk_record_success] %></p>

      <% @matter.business_talk_records.order(end_time: :desc).first(1).each do |business_talk_record| %>
      <%= render partial: "shared/business_talk_record_list", locals: { business_talk_record: business_talk_record } %>
      <% end %>
      <div class="all-client">
        <%= link_to "この案件の商談記録一覧を開く", matter_business_talk_records_path(@matter.id), class:"all-client-link" %>
      </div>
    </div>
  </div>
</div>
<%= render "shared/footer" %>