config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: "matters#index"
  resources :matters do
      resources :clients, except: [:show]
      resources :business_talk_records, except: [:show]
      resources :sales_staffs, only: [:edit, :update]
    collection do
      get 'search'
      post 'search'
    end
  end
  get 'clients', to: 'matters#new_client'
  post 'clients', to: 'matters#create_client'
  get 'sales_staffs', to: 'matters#new_sales_staff'
  post 'sales_staffs', to: 'matters#create_sales_staff'
  resources :users, only: [:show, :edit, :update]
end

app/views/shared/_business_talk_record_form.html.erb
<% if flash[:incorrect_time].present? %>
<p class="client-not-unique-message"><%= flash[:incorrect_time] %></p>
<% else %>
<%= render "shared/error_messages", model: @business_talk_record %>
<% end %>
<table class="matter-table">
  <tr class="matter-table-row-low">
    <th>開始時刻
      <span class="hissu">必須</span>
    </th>
    <td><%= f.datetime_field :start_time, class:"matter-text-field" %>
    </td>
  </tr>
  <tr class="matter-table-row-low">
    <th>終了時刻
      <span class="hissu">必須</span>
    </th>
    <td><%= f.datetime_field :end_time, class:"matter-text-field" %>
    </td>
  </tr>
  <tr class="matter-table-row-high">
    <th>商談内容
      <span class="hissu">必須</span>
    </th>
    <td><%= f.text_area :explain, class:"matter-text-area-high" %>
    </td>
  </tr>
  <tr class="matter-table-row-low">
    <th>商談資料<br>
      <p class="file-explain">(複数ファイル選択できます)
      </p>
    </th>
    <td>
      <%= f.file_field :files, multiple: true, id:"business_talk_record-file" %>
    </td>
  </tr>
  <% if @business_talk_record.files.present? %>
  <tr class="matter-information-table-row-high">
    <th>アップロード済み資料<br>
      <p class="file-explain">不要なファイルはチェックしてください
      </p>
    </th>
    <td>
      <% @business_talk_record.files.each do |file|%>
      <%= f.check_box :file_ids, {:multiple => true}, file.id, false %>
      <%= file.filename %><br>
      <% end %>
    </td>
  </tr>
  <% end %>
</table>

app/views/shared/_business_talk_record_list.html.erb
<table class="business-talk-record-table">
  <tr class="matter-information-table-row-low">
    <th>開始時刻</th>
    <td> <%= business_talk_record.start_time.strftime("%Y-%m-%d %H:%M") %>
    </td>
    <td class="link-td">
      <% if current_user.administrator_id == 2 || @matter.user == current_user%>
      <%= link_to image_tag("edit-icon"), edit_matter_business_talk_record_path(matter_id: @matter.id, id: business_talk_record.id), class:"client-edit-link" %>
      <%= link_to image_tag("delete-icon"), matter_business_talk_record_path(matter_id: @matter.id, id: business_talk_record.id), method: :delete, data: {confirm: "削除しますか？"}, class:"client-edit-link" %>
      <% end %>
    </td>
  </tr>
  <tr class="matter-information-table-row-low">
    <th>終了時刻</th>
    <td colspan="2">
      <%= business_talk_record.end_time.strftime("%Y-%m-%d %H:%M") %>
    </td>
  </tr>
  <tr class="matter-information-table-row-high">
    <th>商談内容</th>
    <td colspan="2">
      <%= simple_format(business_talk_record.explain) %>
    </td>
  </tr>
  <% if business_talk_record.files.present? %>
  <% if business_talk_record.files.size > 2 %>
  <% files = business_talk_record.files.first(2) %>
  <% else %>
  <% files = business_talk_record.files.first(1) %>
  <% end %>
  <% files.each.with_index(1) do |file, i|%>
  <tr class="file-links">
    <th>
      <%="資料#{i}"%>
    </th>
    <td colspan="2">
      <%= link_to rails_blob_path(file), class:"business_talk_record-edit-link"  do %>
      <%= image_tag 'file-icon' %>
      <%= file.filename %>
      <% end %>
      <% if i == 2 %>
      <p class="other_files">
        <%= link_to "その他#{business_talk_record.files.size - i}点", matter_business_talk_records_path(@matter.id) %>
      </p>
      <% end %>
    </td>
  </tr>
  <% end %>
  <% else %>
  <tr>
    <th>資料</th>
    <td colspan="2">
      なし
    </td>
  </tr>
  <% end %>
</table>

app/views/shared/_client_form.html.erb
<% if flash[:client_not_unique].present? || flash[:client_not_editted].present? %>
<p class="client-not-unique-message"><%= flash[:client_not_unique] %></p>
<p class="client-not-unique-message"><%= flash[:client_not_editted] %></p>
<% else %>
<%= render "shared/error_messages", model: @client %>
<% end %>
<table class="matter-table">
  <tr class="matter-table-row-low">
    <th>会社名
      <span class="hissu">必須</span>
    </th>
    <td><%= f.text_field :company, class:"matter-text-field", id:"client_company" %>
    </td>
  </tr>
  <tr class="matter-table-row-middle">
    <th>部署・役職
      <span class="hissu">必須</span>
    </th>
    <td><%= f.text_area :department, class:"matter-text-area-middle", id:"client_department" %>
    </td>
  </tr>
  <tr class="matter-table-row-low">
    <th>担当者
      <span class="hissu">必須</span>
    </th>
    <td><%= f.text_field :name, class:"matter-text-field", id:"client_name" %>
    </td>
  </tr>
</table>

app/views/shared/_client_list.html.erb
<table class="client-information-table">
  <tr class="matter-information-table-row-low">
    <th>会社名</th>
    <td> <%= matter_client.client.company %>
    </td>
    <td class="link-td">
      <% if current_user.administrator_id == 2 || @matter.user == current_user%>
      <%= link_to image_tag("edit-icon"), edit_matter_client_path(matter_id: @matter.id, id: matter_client.client_id), class:"client-edit-link" %>
      <%= link_to image_tag("delete-icon"), matter_client_path(matter_id: @matter.id, id: matter_client.client_id), method: :delete, data: {confirm: "削除しますか？"}, class:"client-edit-link" %>
      <% end %>
    </td>
  </tr>
  <tr class="matter-information-table-row-middle">
    <th>部署・役職</th>
    <td colspan="2">
      <%= matter_client.client.department %>
    </td>
  </tr>
  <tr class="matter-information-table-row-low">
    <th>担当者</th>
    <td colspan="2">
      <%= matter_client.client.name %>
    </td>
  </tr>
</table>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer-main">
  <p class="copyright">
    COPYRIGHT © ◯◯◯◯◯◯◯ Inc. All rights Reserved.
  </p>
</footer>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='header-main'>
  <div class='nav'>
    <ul class='header-left'>
      <li><%= link_to 'TOP', root_path, class: "header-link" %>
      </li>
      <li><%= link_to '案件登録', new_matter_path, class: "header-link" %>
      </li>
      <li><%= link_to '案件検索', search_matters_path, class: "header-link" %>
      </li>
    </ul>
    <ul class='header-right'>
      <li>
        <%= link_to user_path(current_user.id), class: "mypage-link header-link" do %>
        <%= image_tag current_user.user_image, class:"user-icon" %>
        <%="#{current_user.family_name}さんのマイページ"%>
        <% end %>
      </li>
      <li>
        <%= link_to destroy_user_session_path, method: :delete, data: {confirm: "ログアウトしますか？"}, class: "header-link" do %>
        <p>ログアウト</p>
        <% end %>
      </li>
    </ul>
  </div>
</header>

app/views/shared/_matter_form.html.erb
<%= render "shared/error_messages", model: @matter %>
<table class="matter-table">
  <tr class="matter-table-row-low">
    <th>案件名
      <span class="hissu">必須</span>
    </th>
    <td><%= f.text_field :matter_name, class:"matter-text-field", id:"matter_name" %>
    </td>
  </tr>
  <tr class="matter-table-row-high">
    <th>案件詳細</th>
    <td>
      <%= f.text_area :matter_explain, class:"matter-text-area-high", id:"matter_explain" %>
    </td>
  </tr>
  <tr class="matter-table-row-low">
    <th>商材名
      <span class="hissu">必須</span>
    </th>
    <td>
      <%= f.text_field :product, class:"matter-text-field", id:"product" %>
    </td>
  </tr>
  <tr class="matter-table-row-low">
    <th>販売金額見込み(千円)</th>
    <td><%= f.text_field :sale_price, class:"matter-text-field", id:"sale_price" %>
    </td>
  </tr>
  <tr class="matter-table-row-low">
    <th>利益見込み(千円)</th>
    <td><%= f.text_field :profit_price, class:"matter-text-field", id:"profit_price" %>
    </td>
  </tr>
  <tr class="matter-table-row-low">
    <th>販売時期見込み
      <span class="hissu">必須</span>
    </th>
    <td>
      <%= raw sprintf( f.date_select( :sale_time, { use_month_numbers: true, discard_day: true, start_year: 2020,end_year: Time.zone.now.year+10, date_separator:'%s'}, 
            {class:"matter-date"}),'<p class="matter-date-unit">年</p>', '') + '<p class="matter-date-unit">月</p>' %>
    </td>
  </tr>
  <tr class="matter-table-row-low">
    <th>重点度
      <span class="hissu">必須</span>
    </th>
    <td>
      <%= f.collection_select :priority_id, Priority.all, :id, :name %>
    </td>
  </tr>
  <tr class="matter-table-row-low">
    <th>確度
      <span class="hissu">必須</span>
    </th>
    <td>
      <%= f.collection_select :reliability_id, Reliability.all, :id, :name %>
    </td>
  </tr>
  <tr class="matter-table-row-low">
    <th>進捗
      <span class="hissu">必須</span>
    </th>
    <td>
      <%= f.collection_select :progress_id, Progress.all, :id, :name %>
    </td>
  </tr>
  <tr class="matter-table-row-low">
    <th>きっかけ
      <span class="hissu">必須</span>
    </th>
    <td>
      <%= f.text_field :occasion, class:"matter-text-field" %>
    </td>
  </tr>
</table>

app/views/shared/_matter_information_side.html.erb
<div class="sidebar">
  <ul>
    <li>
      <%= link_to "案件情報", matter_path(matter.id), class:"sidebar-link", id:"matter-information-link" %>
    </li>
    <% if current_user.administrator_id == 2 || matter.user == current_user%>
    <li>
      <%= link_to "案件情報編集", edit_matter_path(matter.id), class:"sidebar-link" %></li>
    </li>
    <li>
      <%= link_to "担当営業情報編集", edit_matter_sales_staff_path(matter_id: matter.id, id: matter.sales_staff_id), class:"sidebar-link" %>
    </li>
    <li>
      <%= link_to "顧客情報追加", new_matter_client_path(matter.id), class:"sidebar-link" %></li>
    </li>
    <% end %>
    <li>
      <%= link_to "顧客情報一覧", matter_clients_path(matter.id), class:"sidebar-link", id:"client-list-link" %></li>
    </li>
    <% if current_user.administrator_id == 2 || matter.user == current_user%>
    <li>
      <%= link_to "商談記録登録", new_matter_business_talk_record_path(matter.id), class:"sidebar-link" %></li>
    </li>
    <% end %>
    <li>
      <%= link_to "商談記録一覧", matter_business_talk_records_path(matter.id), class:"sidebar-link", id:"business_talk_record-list-link" %>
    </li>
    <% if current_user.administrator_id == 2 %>
    <li>
      <%= link_to "案件削除", matter_path(matter.id), method: :delete, data: {confirm: "削除しますか？"}, class:"sidebar-link" %>
    </li>
    <% end %>
  </ul>
  </ul>
</div>

app/views/shared/_matter_list.html.erb
<%= link_to matter_path(matter.id), class: "matter-link" do %>
<div class="matter-list">
  <table class="matter-list-table">
    <tr>
      <th>
        <%= link_to user_path(matter.user_id) do%>
        <%= image_tag matter.user.user_image, class:"matter-list-icon" %>
        <% end %>
      </th>
      <td>
        <%= matter.matter_name.truncate(20) %>
      </td>
    </tr>
    <tr>
      <th>販売金額 <p class="price-unit">(千円)</p>
      </th>
      <td><% if matter.sale_price.present? %>
        <%= "¥#{matter.sale_price.to_s(:delimited, delimiter: ',')}" %>
        <% else %>
        未定
        <% end %>
      </td>
    </tr>
    <tr>
      <th>重点度</th>
      <td><%= matter.priority.name %>
      </td>
    </tr>
    <tr>
      <th>進捗</th>
      <td><%= matter.progress.name %>
      </td>
    </tr>
    <tr>
      <th>きっかけ</th>
      <td><%= matter.occasion.truncate(11) %>
      </td>
    </tr>
  </table>
  <div class="matter-create-time">
    <%= "#{matter.updated_at.strftime("%Y-%m-%d %H:%M")}更新" %>
  </div>
</div>
<%end%>

app/views/shared/_matter_search_form.html.erb
<div class="search-form-sort">
  <%= f.select :sorts, {'並び替え': 'id desc', '更新(降順)': 'updated_at desc', '更新(昇順)': 'updated_at asc', '販売金額(昇順)': 'sale_price asc' , '販売金額(降順)': 'sale_price desc', '利益(昇順)': 'profit_price asc' , '利益(降順)': 'profit_price desc' },
   { selected: params[:q][:sorts] },{ class:"sort-form"} %>
  <%= f.submit '並び替え実行', class:"sort-button" %>
</div>
<div class="search-form">
  <label class="search-title"><%= f.label :matter_name_or_matter_explain, "案件名・案件詳細" %>
  </label>
  <%= f.search_field :matter_name_or_matter_explain_cont, class: "search-form-large", placeholder:"キーワードを入力" %>
</div>
<div class="search-form">
  <label class="search-title"><%= f.label :product, "商材" %>
  </label>
  <%= f.search_field :product_cont, class: "search-form-large", placeholder:"キーワードを入力" %>
</div>
<div class="search-form">
  <%= f.label :sale_price, "販売金額見込み", class:"search-title" %>
  <%= f.text_field :sale_price_gteq, class: "search-form-medium" %><p class="search-price-unit">(千円)〜</p>
  <%= f.text_field :sale_price_lteq, class: "search-form-medium" %><p class="search-price-unit">(千円)</p>
</div>
<div class="search-form">
  <%= f.label :profit_price, "利益見込み", class:"search-title"  %>
  <%= f.text_field :profit_price_gteq, class: "search-form-medium" %><p class="search-price-unit">(千円)〜</p>
  <%= f.text_field :profit_price_lteq, class: "search-form-medium" %><p class="search-price-unit">(千円)</p>
</div>
<div class="search-form">
  <%= f.label :sale_time, "販売時期", class:"search-title" %>
  <p class="search-form-date">
    <%= raw sprintf( f.date_select( :sale_time_gteq, { use_month_numbers: true, discard_day: true, prompt:'--',start_year: 2020,end_year: Time.zone.now.year+10, date_separator:'%s'}, 
            {class:"search-form-small"}),'<p class="search-date-unit">年</p>', '') + '<p class="search-date-unit">月〜</p>' %>
  </p>
  <p class="search-form-date">
    <%= raw sprintf( f.date_select( :sale_time_lteq, { use_month_numbers: true, discard_day: true, prompt:'--',start_year: 2020,end_year: Time.zone.now.year+10, date_separator:'%s'},
            {class:"search-form-small"}),'<p class="search-date-unit">年</p>', '') + '<p class="search-date-unit">月</p>' %>
  </p>
</div>
<div class="search-form">
  <%= f.label :priority_id_eq, "重点度",  class:"search-title" %>
  <div class="form-checks">
    <%= f.collection_check_boxes :priority_id_eq_any, @priority_id, :id, :name, { include_hidden: false, multiple: true } do |b| %>
    <div class="form-check-small">
      <%= b.label class: "form-check-label" do %>
      <%= b.check_box class: "form-check-input" %>
      <%= b.text %>
      <% end %>
    </div>
    <% end %>
  </div>
</div>
<div class="search-form">
  <%= f.label :reliability_id, "確度",  class:"search-title" %>
  <div class="form-checks">
    <%= f.collection_check_boxes :reliability_id_eq_any, @reliability_id, :id, :name, { include_hidden: false, multiple: true } do |b| %>
    <div class="form-check-small">
      <%= b.label class: "form-check-label" do %>
      <%= b.check_box class: "form-check-input" %>
      <%= b.text %>
      <% end %>
    </div>
    <% end %>
  </div>
</div>
<div class="search-form">
  <%= f.label :progress_id, "進捗",  class:"search-title" %>
  <div class="form-checks">
    <%= f.collection_check_boxes :progress_id_eq_any, @progress_id, :id, :name, { include_hidden: false, multiple: true } do |b| %>
    <div class="form-check-large">
      <%= b.label class: "form-check-label" do %>
      <%= b.check_box class: "form-check-input" %>
      <%= b.text %>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

<div class="search-form">
  <%= f.label :occasion, "きっかけ", class:"search-title" %>
  <%= f.search_field :occasion_cont, class: "search-form-large", placeholder:"キーワードを入力"  %>
</div>
<div class="search-form">
  <%= f.label :user_family_name_or_user_first_name, "担当者", class:"search-title" %>
  <%= f.search_field :user_family_name_or_user_first_name_cont, class: "search-form-large", placeholder:"キーワードを入力"  %>
</div>
<div class="search-form">
  <p class="search-accordion-button">▽顧客検索フォーム表示</p>
  <div class="search-sales-form">
    <%= f.label :clients_company, "会社", class:"search-title" %>
    <%= f.search_field :clients_company_cont, class: "search-form-large", placeholder:"キーワードを入力"  %>
    <%= f.label :clients_department, "部署", class:"search-title" %>
    <%= f.search_field :clients_department_cont, class: "search-form-large", placeholder:"キーワードを入力"  %>
    <%= f.label :clients_name, "担当者", class:"search-title" %>
    <%= f.search_field :clients_name_cont, class: "search-form-large", placeholder:"キーワードを入力"  %>
  </div>
</div>
<div class="search-form">
  <p class="search-accordion-button">▽担当営業検索フォーム表示</p>
  <div class="search-sales-form">
    <%= f.label :sales_staff_department, "部署・役職", class:"search-title" %>
    <%= f.search_field :sales_staff_department_cont, class: "search-form-large", placeholder:"キーワードを入力"  %>
    <%= f.label :sales_staff_staff, "部署・役職", class:"search-title" %>
    <%= f.search_field :sales_staff_staff_cont, class: "search-form-large", placeholder:"キーワードを入力"  %>
  </div>
</div>


<%= f.submit '検索', class:"search-button" %>
<%= f.submit 'リセット', class:"search-button" %>

app/views/shared/_mypage_side.html.erb
<div class="sidebar">
  <ul>
    <li>
      <%= link_to "基本情報", user_path(params[:id]), class:"sidebar-link", id:"user-information-link" %></li>
    </li>
    <li>
      <%= link_to "案件一覧", search_matters_path(user_id: @user.id),class:"sidebar-link" %></li>
    </li>
    <% if(current_user == @user) %>
    <li><%= link_to "ユーザー情報編集", edit_user_registration_path, class:"sidebar-link" %></li>
    </li>
    <% end %>
  </ul>
</div>

app/views/shared/_sales_staff_form.html.erb
<%= render "shared/error_messages", model: @sales_staff %>
<table class="matter-table">
  <tr class="matter-table-row-middle">
    <th>部署・役職
      <span class="hissu">必須</span>
    </th>
    <td><%= f.text_area :department, class:"matter-text-area-middle", id:"sales_department" %>
    </td>
  </tr>
  <tr class="matter-table-row-low">
    <th>営業スタッフ
      <span class="hissu">必須</span>
    </th>
    <td><%= f.text_field :staff, class:"matter-text-field", id:"staff" %>
    </td>
  </tr>
</table>